export default {
    SET_BOARD: "SET_BOARD",
    SET_CURRENT_BOARD: "SET_CURRENT_BOARD",
    SET_SELECTED_TASK: "SET_SELECTED_TASK",
    SET_SELECTED_TASK_INDEX: "SET_SELECTED_TASK_INDEX",
    SET_SELECTED_LIST_INDEX: "SET_SELECTED_LIST_INDEX",
};
